# Generated by Django 4.2.13 on 2024-07-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApi', '0007_userpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
