# Generated by Django 4.2.13 on 2024-07-09 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApi', '0009_device'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='token',
            new_name='token_device',
        ),
    ]
