# Generated by Django 5.0.6 on 2024-06-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupe', '0004_alter_groupe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupe',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
