# Generated by Django 5.0.6 on 2024-06-24 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupe', '0007_rename_image_groupepublication_group_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupepublication',
            old_name='group_pic',
            new_name='image',
        ),
    ]
