version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/bytebelt  
    depends_on:
      - db
  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: bytebelt
      POSTGRES_PASSWORD: bytebelt
      POSTGRES_DB: bytebelt
  #pgamdin:
  #  image: dpage/pgadmin4
  #  ports:
  #    - "5050:5050"
  #  environment:
  #    PGADMIN_DEFAULT_EMAIL: audesandrine6@gmail.com
  #    PGADMIN_DEFAULT_PASSWORD: aude123
