name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
    #- name: Run Tests
    #  run: |
    #    python ./bytebelt/manage.py test
    - name: Start Django Server with Docker  
      run: |
        cd ./bytebelt/
        docker-compose up -d   
        sleep 30

    - name: Test endpoint
      run: |
        site_online=$(curl -o /dev/null -s -w "%{http_code}\n" http://localhost:80)
        if [[ "$site_online" =~ ^4 ]] || [[ "$site_online" =~ ^5 ]]; then
          echo "Test Failed $site_online"
          exit 1
        else
          echo "Test Ok $site_online"
        fi
