name: Build and Push Docker Image

on:
  push:
    branches:
      - azure

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: aperano
          password: dckr_pat_tOyTOPXz3VYOUy_cnmCo5AlQ6lk

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push to Docker Compose Hub
        uses: docker/build-push-action@v5
        with:
          context: ./bytebelt
          push: true
          tags: aperano/bytebelt:latest

      - name : Test for docker-compose file
        run: |
          cd ./bytebelt/
          docker-compose up -d
          sleep 30
          site_online=$(curl -o /dev/null -s -w "%{http_code}\n" http://localhost:80)
          if [[ "$site_online" =~ ^4 ]] || [[ "$site_online" =~ ^5 ]]; then
            echo "Test Failed $site_online"
            exit 1
          else
            echo "Test Ok $site_online"
          fi
